### ISSUE TITLE
fcms plugin using player location instead of carrier location when posting jump into discord 

### ISSUE THREAD

**Issue by LexRottie** [anthonylangsworth/FCMS#5]
As the title says the plugin seams to be using the player location instead of the carrier location in the departing section of the discord post

**Comment by anthonylangsworth** [comment]
Thanks for raising the issue. Unfortunately, this is a known issue, as per the README.

The problem is the https://fleetcarrier.space API the plug-in calls requires the current location of the carrier.  Unfortunately, neither the **Elite: Dangerous** client nor EDMC know the location of your carrier. Therefore, the best guess is the current system your commander is in. EDMC and the **Elite: Dangerous** journal file both provide this. See https://github.com/FuelRats/FCMS/blob/master/FCMS/views/api.py if you can read Python and are interested in the internals.

I apologise that we cannot do any better.

**Comment by LexRottie** [comment]
No probs hopefully they will add that info for it to pull

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by anthonylangsworth** [comment]
Thanks for your understanding.
